/* tslint:disable */

import React from 'react';
import './font.css';
import './fonts/ADLaM_Display/ADLaMDisplay-Regular.ttf'
import './fonts/Akronim/Akronim-Regular.ttf'
import './fonts/Allerta_Stencil/AllertaStencil-Regular.ttf'
import './fonts/Amatic_SC/AmaticSC-Regular.ttf'
import './fonts/Audiowide/Audiowide-Regular.ttf'
import './fonts/Bagel_Fat_One/BagelFatOne-Regular.ttf'
import './fonts/Barriecito/Barriecito-Regular.ttf'
import './fonts/Barrio/Barrio-Regular.ttf'
import './fonts/Beth_Ellen/BethEllen-Regular.ttf'
import './fonts/Black_Ops_One/BlackOpsOne-Regular.ttf'
import './fonts/Bungee_Outline/BungeeOutline-Regular.ttf'
import './fonts/Bungee_Shade/BungeeShade-Regular.ttf'
import './fonts/Cabin_Sketch/CabinSketch-Regular.ttf'
import './fonts/Ceviche_One/CevicheOne-Regular.ttf'
import './fonts/Cinzel_Decorative/CinzelDecorative-Regular.ttf'
import './fonts/Codystar/Codystar-Regular.ttf'
import './fonts/Comforter/Comforter-Regular.ttf'
import './fonts/Dancing_Script/static/DancingScript-Regular.ttf'
import './fonts/Edu_SA_Beginner/static/EduSABeginner-Regular.ttf'
import './fonts/Exo_2/static/Exo2-Regular.ttf'
import './fonts/Faster_One/FasterOne-Regular.ttf'
import './fonts/Fredericka_the_Great/FrederickatheGreat-Regular.ttf'
import './fonts/Gamja_Flower/GamjaFlower-Regular.ttf'
import './fonts/Geo/Geo-Regular.ttf'
import './fonts/Gluten/static/Gluten-Regular.ttf'
import './fonts/Gochi_Hand/GochiHand-Regular.ttf'
import './fonts/Hachi_Maru_Pop/HachiMaruPop-Regular.ttf'
import './fonts/Handjet/static/Handjet-Regular.ttf'
import './fonts/Homemade_Apple/HomemadeApple-Regular.ttf'
import './fonts/Hurricane/Hurricane-Regular.ttf'
import './fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf'
import './fonts/Irish_Grover/IrishGrover-Regular.ttf'
import './fonts/Jacques_Francois_Shadow/JacquesFrancoisShadow-Regular.ttf'
import './fonts/Kalam/Kalam-Regular.ttf'
import './fonts/Kumar_One_Outline/KumarOneOutline-Regular.ttf'
import './fonts/La_Belle_Aurore/LaBelleAurore-Regular.ttf'
import './fonts/Libre_Barcode_39_Extended_Text/LibreBarcode39ExtendedText-Regular.ttf'
import './fonts/Libre_Barcode_39_Text/LibreBarcode39Text-Regular.ttf'
import './fonts/Londrina_Shadow/LondrinaShadow-Regular.ttf'
import './fonts/Luckiest_Guy/LuckiestGuy-Regular.ttf'
import './fonts/Megrim/Megrim-Regular.ttf'
import './fonts/Metamorphous/Metamorphous-Regular.ttf'
import './fonts/Moirai_One/MoiraiOne-Regular.ttf'
import './fonts/Monofett/Monofett-Regular.ttf'
import './fonts/Monoton/Monoton-Regular.ttf'
import './fonts/Monsieur_La_Doulaise/MonsieurLaDoulaise-Regular.ttf'
import './fonts/Mountains_of_Christmas/MountainsofChristmas-Regular.ttf'
import './fonts/Mystery_Quest/MysteryQuest-Regular.ttf'
import './fonts/Nosifer/Nosifer-Regular.ttf'
import './fonts/Nothing_You_Could_Do/NothingYouCouldDo-Regular.ttf'
import './fonts/Orbitron/static/Orbitron-Regular.ttf'
import './fonts/Pacifico/Pacifico-Regular.ttf'
import './fonts/Parisienne/Parisienne-Regular.ttf'
import './fonts/Petit_Formal_Script/PetitFormalScript-Regular.ttf'
import './fonts/Philosopher/Philosopher-Regular.ttf'
import './fonts/Phudu/static/Phudu-Regular.ttf'
import './fonts/Press_Start_2P/PressStart2P-Regular.ttf'
import './fonts/Qwitcher_Grypen/QwitcherGrypen-Regular.ttf'
import './fonts/Racing_Sans_One/RacingSansOne-Regular.ttf'
import './fonts/Reenie_Beanie/ReenieBeanie-Regular.ttf'
import './fonts/Rubik_80s_Fade/Rubik80sFade-Regular.ttf'
import './fonts/Rubik_Iso/RubikIso-Regular.ttf'
import './fonts/Rubik_Pixels/RubikPixels-Regular.ttf'
import './fonts/Saira_Stencil_One/SairaStencilOne-Regular.ttf'
import './fonts/Sedgwick_Ave_Display/SedgwickAveDisplay-Regular.ttf'
import './fonts/Shalimar/Shalimar-Regular.ttf'
import './fonts/Silkscreen/Silkscreen-Regular.ttf'
import './fonts/Slackey/Slackey-Regular.ttf'
import './fonts/Special_Elite/SpecialElite-Regular.ttf'
import './fonts/Stick/Stick-Regular.ttf'
import './fonts/Tangerine/Tangerine-Regular.ttf'
import './fonts/Tilt_Prism/static/TiltPrism-Regular.ttf'
import './fonts/Train_One/TrainOne-Regular.ttf'
import './fonts/UnifrakturMaguntia/UnifrakturMaguntia-Regular.ttf'
import './fonts/Vast_Shadow/VastShadow-Regular.ttf'
import './fonts/Yatra_One/YatraOne-Regular.ttf'
import './fonts/Yellowtail/Yellowtail-Regular.ttf'
import './fonts/Zen_Tokyo_Zoo/ZenTokyoZoo-Regular.ttf'
import './fonts/Zeyada/Zeyada-Regular.ttf'

const fontClasses = ["ADLaM_Display", "Akronim", "Allerta_Stencil", "Amatic_SC", "Audiowide", "Bagel_Fat_One", "Barriecito", "Barrio", "Beth_Ellen", "Black_Ops_One", "Bungee_Outline", "Bungee_Shade", "Cabin_Sketch", "Ceviche_One", "Cinzel_Decorative", "Codystar", "Comforter", "Dancing_Script", "Edu_SA_Beginner", "Exo_2", "Faster_One", "Fredericka_the_Great", "Gamja_Flower", "Geo", "Gluten", "Gochi_Hand", "Hachi_Maru_Pop", "Handjet", "Homemade_Apple", "Hurricane", "IBM_Plex_Mono", "Irish_Grover", "Jacques_Francois_Shadow", "Kalam", "Kumar_One_Outline", "La_Belle_Aurore", "Libre_Barcode_39_Extended_Text", "Libre_Barcode_39_Text", "Londrina_Shadow", "Luckiest_Guy", "Megrim", "Metamorphous", "Moirai_One", "Monofett", "Monoton", "Monsieur_La_Doulaise", "Mountains_of_Christmas", "Mystery_Quest", "Nosifer", "Nothing_You_Could_Do", "Orbitron", "Pacifico", "Parisienne", "Petit_Formal_Script", "Philosopher", "Phudu", "Press_Start_2P", "Qwitcher_Grypen", "Racing_Sans_One", "Reenie_Beanie", "Rubik_80s_Fade", "Rubik_Iso", "Rubik_Pixels", "Saira_Stencil_One", "Sedgwick_Ave_Display", "Shalimar", "Silkscreen", "Slackey", "Special_Elite", "Stick", "Tangerine", "Tilt_Prism", "Train_One", "UnifrakturMaguntia", "Vast_Shadow", "Yatra_One", "Yellowtail", "Zen_Tokyo_Zoo", "Zeyada",];


export const Font = (props: {ch: string}) => {
    const {ch} = props;
    const font = fontClasses[Math.floor(Math.random() * fontClasses.length)];
    const fontSize = Math.floor(Math.random() * 100) + 10;
    return (
        <span className={font} style={{fontSize}}>{ch}</span>
    );
}
